import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'truecyber',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div 
          style={{
            backgroundImage: "url(/images/red1.jpg)",
            backgroundSize: "contain",  // Use "contain" instead of "cover"
            backgroundPosition: "center",
            minHeight: "100vh",
          }}
        >
          {children}
        </div>
      </body>
    </html>
  )
}
